name: tf
channels:
  - defaults
dependencies:
  - _tflow_select=2.2.0
  - abseil-cpp=20211102.0
  - aiosignal=1.2.0
  - astunparse=1.6.3
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cachetools=4.2.2
  - charset-normalizer=2.0.4
  - dataclasses=0.8
  - fftw=3.3.9
  - flatbuffers=2.0.0
  - gast=0.4.0
  - giflib=5.2.1
  - google-auth=2.6.0
  - google-auth-oauthlib=0.4.4
  - google-pasta=0.2.0
  - grpc-cpp=1.46.1
  - hdf5=1.10.6
  - icu=58.2
  - intel-openmp=2021.4.0
  - jpeg=9e
  - keras-preprocessing=1.1.2
  - krb5=1.19.2
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libedit=3.1.20210910
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libnghttp2=1.46.0
  - libpng=1.6.37
  - libprotobuf=3.20.1
  - libssh2=1.10.0
  - llvm-openmp=14.0.6
  - mkl=2021.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - numpy-base=1.22.3
  - openssl=1.1.1s
  - opt_einsum=3.3.0
  - packaging=21.3
  - pyasn1=0.4.8
  - pyasn1-modules=0.2.8
  - pycparser=2.21
  - pyopenssl=22.0.0
  - python=3.10.8
  - python-flatbuffers=1.12
  - re2=2022.04.01
  - readline=8.2
  - requests-oauthlib=1.3.0
  - rsa=4.7.2
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.40.0
  - tensorboard-plugin-wit=1.6.0
  - tensorflow-base=2.9.1
  - tk=8.6.12
  - typing_extensions=4.3.0
  - tzdata=2022f
  - werkzeug=2.0.3
  - wheel=0.35.1
  - xz=5.2.6
  - yaml=0.2.5
  - zlib=1.2.13
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.1
    - appnope==0.1.3
    - asttokens==2.2.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - backcall==0.2.0
    - blinker==1.4
    - brotlipy==0.7.0
    - certifi==2022.9.24
    - cffi==1.15.1
    - click==8.0.4
    - contourpy==1.0.6
    - cryptography==38.0.1
    - cvxopt==1.3.0
    - cycler==0.11.0
    - debugpy==1.6.4
    - decorator==5.1.1
    - DeepKnockoffs==0.1.0
    - entrypoints==0.4
    - executing==1.2.0
    - fonttools==4.38.0
    - frozenlist==1.2.0
    - grpcio==1.42.0
    - h5py==3.7.0
    - idna==3.4
    - importlib-metadata==4.11.3
    - ipykernel==6.17.1
    - ipython==8.7.0
    - jedi==0.18.2
    - jupyter-client==7.4.7
    - jupyter-core==5.1.0
    - keras==2.9.0
    - kiwisolver==1.4.4
    - markdown==3.3.4
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mkl-fft==1.3.1
    - mkl-random==1.2.2
    - mkl-service==2.4.0
    - multidict==6.0.2
    - nest-asyncio==1.5.6
    - numpy==1.22.3
    - oauthlib==3.2.1
    - pandas==1.5.2
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - pip==22.2.2
    - platformdirs==2.5.4
    - prompt-toolkit==3.0.33
    - protobuf==3.20.1
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pygments==2.13.0
    - pyjwt==2.4.0
    - pyparsing==3.0.9
    - pysocks==1.7.1
    - python-dateutil==2.8.2
    - pytz==2022.6
    - pyyaml==6.0
    - pyzmq==24.0.1
    - requests==2.28.1
    - scipy==1.7.3
    - setuptools==65.5.0
    - stack-data==0.6.2
    - tensorboard==2.9.0
    - tensorboard-data-server==0.6.0
    - tensorflow==2.9.1
    - tensorflow-estimator==2.9.0
    - termcolor==2.1.0
    - torch==1.13.0
    - tornado==6.2
    - traitlets==5.6.0
    - typing-extensions==4.3.0
    - urllib3==1.26.12
    - wcwidth==0.2.5
    - wrapt==1.14.1
    - yarl==1.8.1
    - zipp==3.8.0

